version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: node:16.16.0

    working_directory: ~/bingocard_frontend

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - bingocard_frontend-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test