version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: node:16.16.0

    working_directory:
    steps:
      - checkout
      - run: npm install

      # run tests!
      - run: npm run test --passWithNoTests
